# Generated by Django 5.2.3 on 2025-10-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Prospect', 'Prospect'), ('Customer', 'Customer')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
